name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@77.232.136.158 << 'EOF'
            cd /root/projects/adekkdev-back
            git reset --hard
            git clean -fd
            git pull origin main
            composer install --optimize-autoloader --no-dev
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            docker-compose down
            docker-compose up --build -d
            docker-compose exec -T backend php artisan migrate --force
          EOF
